# https://github.com/kubernetes/sample-controller/issues/6
required = [
  "k8s.io/code-generator/cmd/client-gen"
]

# https://github.com/kubernetes/code-generator/issues/6
[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

# FIXME: Following https://github.com/kubernetes/apimachinery/issues/46 to get around 
#   unknown field 'CaseSensitive' in struct literal error when bringing in apimachinery 1.11
[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[constraint]]
  name = "istio.io/api"
  branch = "release-1.1"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-8.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "^1.1.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[prune]
  go-tests = true
